name: Send Email on Job Completion

on:
  # This workflow runs every time a push or pull request is made to the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run your build or tests
      run: echo "Running tests or build steps here..."

  send_email:
    runs-on: ubuntu-latest
    needs: build # Ensures that the 'build' job completes first
    steps:
    - name: Send email using SendGrid
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        SENDGRID_FROM_EMAIL: 'testemail@exampleboe.com' # Replace with the sender email
        SENDGRID_TO_EMAIL: 'karvendhan.it@gmail.com' # Replace with the recipient email
      run: |
        echo '{
          "personalizations": [
            {
              "to": [{"email": "'"$SENDGRID_TO_EMAIL"'"}]
            }
          ],
          "from": {"email": "'"$SENDGRID_FROM_EMAIL"'"},
          "subject": "GitHub Actions Job Completed",
          "content": [
            {
              "type": "text/plain",
              "value": "Your GitHub Action job has been completed successfully."
            }
          ]
        }' > email_payload.json

        curl --request POST \
          --url https://api.sendgrid.com/v3/mail/send \
          --header "Authorization: Bearer $SENDGRID_API_KEY" \
          --header 'Content-Type: application/json' \
          --data @email_payload.json
